version: "3.8"

services:
  app:
    container_name: super-dev
    image: super-dev
    build:
      context: .
      target: development
    volumes:
      - ./src:/apps/src
    ports:
      - 3030:3030
